### ISSUE TITLE
<PRUEBA> Registrar un médico

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/CAR#18]

**Comment by felipedonoso** [comment]
@danteghirardelli la prueba consistirá en poder crear un nuevo médico en la plataforma, ingresar su horario laboral y su centro médico.

**Comment by danteghirardelli** [comment]
Se crea un nuevo médico en la plataforma, ingresar su horario laboral y su centro médico.
![image](https://user-images.githubusercontent.com/21196249/50637240-eddfdd00-0f37-11e9-9425-f1f53701acaf.png)
![image](https://user-images.githubusercontent.com/21196249/50637297-2f708800-0f38-11e9-9e9d-07459514dae9.png)
![image](https://user-images.githubusercontent.com/21196249/50637350-7199c980-0f38-11e9-9b8e-3618efe5d015.png)
![image](https://user-images.githubusercontent.com/21196249/50637416-bb82af80-0f38-11e9-9312-5886359275c8.png)
![image](https://user-images.githubusercontent.com/21196249/50637447-d35a3380-0f38-11e9-9bc0-a713f1963684.png)
![image](https://user-images.githubusercontent.com/21196249/50637485-ebca4e00-0f38-11e9-84f5-fba1511cb844.png)
![image](https://user-images.githubusercontent.com/21196249/50637515-0dc3d080-0f39-11e9-8ecb-2570734db2df.png)
![image](https://user-images.githubusercontent.com/21196249/50637566-44015000-0f39-11e9-8940-77f59c6b6232.png)
### No permite crear Médico.
Al Guardar
Sistema envía mensaje:
Error
"Debes completar todos los campos requeridos, Intente Nuevamente".
También indica Solo se pueden ingresar letras.
![image](https://user-images.githubusercontent.com/21196249/50637681-b96d2080-0f39-11e9-825c-1c5fcb65ba22.png)
Al parecer en campo Nombres no permite Tilde.
Mensaje en campo "Solo se pueden ingresar letras".
Se sugiere verificar si campos Apellido Paterno y Apellido Materno.
Tienen el mismo Problema.

**Comment by danteghirardelli** [comment]
@cristsaavedra @felipedonoso 
Según lo conversado con Cristian.
Aún no se puede crear un Médico como tal. Solo se está creando desde el Mantenedor Usuario / Médico.
Tampoco se podrá ingresar su horario laboral ni su centro Médico por lo anteriormente expuesto.
### Por ahora esta tarea #18 quedará STBY.

**Comment by cristsaavedra** [comment]
@danteghirardelli efectivamente el campo nombres no aceptaba tildes, esto se corrige y esta listo para ser probado nuevamente.

**Comment by danteghirardelli** [comment]
### Continuar con las pruebas después de la corrección:

![image](https://user-images.githubusercontent.com/21196249/50768956-15e57e00-1261-11e9-8670-afba5cf3301b.png)
![image](https://user-images.githubusercontent.com/21196249/50769279-3eba4300-1262-11e9-9fc4-dc554bcbb900.png)
![image](https://user-images.githubusercontent.com/21196249/50769444-b8eac780-1262-11e9-9cd0-3d1629fa9b63.png)
![image](https://user-images.githubusercontent.com/21196249/50770633-bc804d80-1266-11e9-886c-d33971f791da.png)
![image](https://user-images.githubusercontent.com/21196249/50770692-f3566380-1266-11e9-8b27-4383959179bf.png)
![image](https://user-images.githubusercontent.com/21196249/50770718-06693380-1267-11e9-9091-2c1608328149.png)
Envía mensaje de error:
![image](https://user-images.githubusercontent.com/21196249/50770818-5d6f0880-1267-11e9-83fa-6dc6a977e68d.png)

No permite continuar con la creación del Profesional.

### Observación
En campo Teléfono se deja un espacio y al parecer esta situación no permite la creación.

### Se sugiere cambiar mensaje de:
Solo se pueden ingresar valores numericos  a "Solo se pueden ingresar valores numéricos"

@felipedonoso @cristsaavedra 

Cristian:
Avísame cuando esté listo y lo veo nuevamente.
Si tienes alguna consulta me dices.

**Comment by danteghirardelli** [comment]
@cristsaavedra  @felipedonoso 

Se sugiere también que en Mantenedor se corrijan las acentuaciones que te copio:
![image](https://user-images.githubusercontent.com/21196249/50772320-20f1db80-126c-11e9-8a33-4c57e65e4dbc.png)

Muchas gracias.

**Comment by danteghirardelli** [comment]
### Se debe registrar un nuevo Médico
Rut 17706106
![image](https://user-images.githubusercontent.com/21196249/50902780-9a1f3900-13fa-11e9-82ea-3eadadd79c03.png)
![image](https://user-images.githubusercontent.com/21196249/50902847-cfc42200-13fa-11e9-8896-8053aaa39263.png)
![image](https://user-images.githubusercontent.com/21196249/50903012-4d882d80-13fb-11e9-8d6d-df46331b5480.png)
![image](https://user-images.githubusercontent.com/21196249/50903102-87593400-13fb-11e9-9d99-66a9af410974.png)
![image](https://user-images.githubusercontent.com/21196249/50903126-993ad700-13fb-11e9-98b7-1c517e33565f.png)
![image](https://user-images.githubusercontent.com/21196249/50903559-e1a6c480-13fc-11e9-960a-8b64a576896e.png)
Profesional ingresado con éxito.

### Editar Apellido de Donoso a Godoy
![image](https://user-images.githubusercontent.com/21196249/50904091-2b43df00-13fe-11e9-9018-f9ad206c6c76.png)
![image](https://user-images.githubusercontent.com/21196249/50904122-3eef4580-13fe-11e9-8853-48b823876173.png)
Se cambia a Godoy
![image](https://user-images.githubusercontent.com/21196249/50904153-57f7f680-13fe-11e9-83e6-02a160d94f81.png)
![image](https://user-images.githubusercontent.com/21196249/50904177-69d99980-13fe-11e9-8c6b-2bc898af6ef8.png)
![image](https://user-images.githubusercontent.com/21196249/50904192-78c04c00-13fe-11e9-8cf2-8069ad9d3599.png)
Datos modificados.
![image](https://user-images.githubusercontent.com/21196249/50904442-0b60eb00-13ff-11e9-8055-6ff1af8a909a.png)
Cambio apellido realizado correctamente.

### Conclusión
Registra correctamente el nuevo Médico.
Aparece dentro del mantenedor con todos los tildes solicitados.

@cristsaavedra muchas gracias por los cambios.
@felipedonoso @cristsaavedra 

Favor cerrar Tarea N°18
