### ISSUE TITLE
<PRUEBA> Registro de un deportista

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/CAR#19]

**Comment by felipedonoso** [comment]
@danteghirardelli similar a lo del registro médico

**Comment by danteghirardelli** [comment]
### Se creará un "Registro de un Deportista" desde Mantenedores / Deportistas
![image](https://user-images.githubusercontent.com/21196249/50641220-0a831180-0f46-11e9-9589-5f0562113c9a.png)
![image](https://user-images.githubusercontent.com/21196249/50641301-44ecae80-0f46-11e9-994c-4c4df2239f8c.png)
![image](https://user-images.githubusercontent.com/21196249/50641453-bb89ac00-0f46-11e9-84c4-01466097022c.png)
![image](https://user-images.githubusercontent.com/21196249/50641543-05729200-0f47-11e9-8186-9693207124f2.png)

### Observaciones
Campo Telefono sin tilde debe decir Teléfono.
Campo Teléfono permite el ingreso de números infinitos.
Se sugiere que permita solo 9 dígitos en caso de ser un Número de Celular(Móvil).
![image](https://user-images.githubusercontent.com/21196249/50641910-3dc6a000-0f48-11e9-9e57-9401591911a9.png)

### Observaciones
Campo Direccion sin tilde debe decir Dirección.
Campo Dirección permite el ingreso de caracteres infinitos(Verificar cuanto serán los necesarios). Con eso se evitará la carga de este campo en la BD.
![image](https://user-images.githubusercontent.com/21196249/50642291-6ef3a000-0f49-11e9-9beb-ee73566871f5.png)
![image](https://user-images.githubusercontent.com/21196249/50642334-921e4f80-0f49-11e9-941f-b0209549d790.png)
![image](https://user-images.githubusercontent.com/21196249/50642417-d9a4db80-0f49-11e9-9192-c94dd4ee229a.png)

### Observación
Campo Ocupacion Deportista sin tilde debe decir Ocupación Deportista.
![image](https://user-images.githubusercontent.com/21196249/50642493-1a045980-0f4a-11e9-9488-a90cdfb40e5f.png)
![image](https://user-images.githubusercontent.com/21196249/50642581-5d5ec800-0f4a-11e9-8017-bd128a8bc370.png)

### Observaciones
Campo Edad Inicio Practica sin tilde debe decir Edad Inicio Práctica.
Campo Años Practicando deporte se sugiere que Deporte comience con Mayúscula.
![image](https://user-images.githubusercontent.com/21196249/50642793-04dbfa80-0f4b-11e9-80aa-046bae892d81.png)

###Observación
Campo Email permite el ingreso de caracteres infinitos.
![image](https://user-images.githubusercontent.com/21196249/50642897-5d12fc80-0f4b-11e9-96c9-be78fd7cff1c.png)
![image](https://user-images.githubusercontent.com/21196249/50642970-892e7d80-0f4b-11e9-8f0f-f692b8e87511.png)

###Observación
Campo Grupo Sanguíneo permite el ingreso de caracteres infinitos.
![image](https://user-images.githubusercontent.com/21196249/50643042-bc710c80-0f4b-11e9-99c9-94ccd782b415.png)

###Observación
Campo Condicion Deportista sin tilde debe decir Condición Deportista.
![image](https://user-images.githubusercontent.com/21196249/50643179-0b1ea680-0f4c-11e9-80b8-7e914f0508f1.png)

![image](https://user-images.githubusercontent.com/21196249/50643200-1ffb3a00-0f4c-11e9-92ab-9816eb8eed79.png)


![image](https://user-images.githubusercontent.com/21196249/50643215-2f7a8300-0f4c-11e9-85df-bc2a547b2d86.png)

Despliega Mensaje de Error no especificado.
Se intenta nuevamente pero error persiste.

@felipedonoso @cristsaavedra 
No se puede avanzar con esta tarea.
Esto debido a que campo Grupo Sanguíneo permite el ingreso de caracteres infinitos. Esto ya fue detectado en las Observaciones informadas.
![image](https://user-images.githubusercontent.com/21196249/50643538-2f2eb780-0f4d-11e9-8c24-854798aeb11c.png)

Se eliminarán los caracteres sobrantes de este campo para poder continuar.
![image](https://user-images.githubusercontent.com/21196249/50643620-63a27380-0f4d-11e9-9721-39baf61f71f3.png)

Se presiona "Guardar"
![image](https://user-images.githubusercontent.com/21196249/50643673-85035f80-0f4d-11e9-9c6a-897d0b64554b.png)
![image](https://user-images.githubusercontent.com/21196249/50643696-90568b00-0f4d-11e9-92d6-1b9aebffcf4e.png)

![image](https://user-images.githubusercontent.com/21196249/50643767-ba0fb200-0f4d-11e9-9037-a53d5e153a3e.png)

Deportista creado Correctamente.

Favor revisar las observaciones comentadas.

@felipedonoso @cristsaavedra 

### Tarea finalizada.

**Comment by cristsaavedra** [comment]
@danteghirardelli Se corrigen las acentuaciones de las palabras y largos de los campos correspondiente al grupo sanguineo, direccion y correo electronico. con respecto al numero telefonico este se encuentra de largo 11 ya que igual manera puedes agregarlo como 56961938399

**Comment by cristsaavedra** [comment]
correcciones realizadas, favor revisar nuevamente.

**Comment by danteghirardelli** [comment]
Cristian, muchas gracias.
Lo revisaré nuevamente y te cuento.

@cristsaavedra @felipedonoso

**Comment by danteghirardelli** [comment]
### Se intenta crear un Deportista con el rut 109667439 quien ya está registrado:
![image](https://user-images.githubusercontent.com/21196249/50830009-29f2b380-1325-11e9-9c78-9694414ffd6f.png)
![image](https://user-images.githubusercontent.com/21196249/50830133-9d94c080-1325-11e9-8166-504b9ba500c3.png)
![image](https://user-images.githubusercontent.com/21196249/50830169-c3ba6080-1325-11e9-93c4-075f1ea9496e.png)
Se completan todos los campos requeridos y después se presiona "Guardar"
![image](https://user-images.githubusercontent.com/21196249/50830408-7db1cc80-1326-11e9-8d58-4f65a54c89ff.png)
![image](https://user-images.githubusercontent.com/21196249/50830433-928e6000-1326-11e9-8ce1-aa72568752d6.png)
Mensaje correcto.
### No permite crear nuevamente a un Deportista ya registrado.

@felipedonoso @cristsaavedra
