### ISSUE TITLE
<PRUEBA> Asignar hora DEPORTISTA

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/CAR#20]

**Comment by danteghirardelli** [comment]
### Desde Horas Médicas/ Reservar Horas Médicas se asignará una Hora para un Deportista

###Observación
Tanto Mantenedor Horas Medicas como los Menús Consultar Horas Medicas,Reservar Horas Medicas y Anular Horas Medicas aparecen sin tilde en la palabra Médicas.
![image](https://user-images.githubusercontent.com/21196249/50644735-766a7780-0f50-11e9-85cb-a1b98a447689.png)

### Reservar Horas Médicas
Se ingresa Rut 10966743
![image](https://user-images.githubusercontent.com/21196249/50644926-09a3ad00-0f51-11e9-8a26-c02744c266c3.png)

![image](https://user-images.githubusercontent.com/21196249/50644965-20e29a80-0f51-11e9-8c74-d39beaa146d0.png)

### Sugerencia
En 1. Identificación del paciente los Botones Atrás y Siguiente están situados muy abajo. Con esto se pierde el foco.

###Observación 
Botón Atras aparece sin tilde debe decir Atrás.
![image](https://user-images.githubusercontent.com/21196249/50645197-b5e59380-0f51-11e9-805c-d66c47df79bb.png)

###Observación
En 2. Selección especialidad o profesional en la Búsqueda por especialidad. Selección Área estas aparecen sin Tilde.
![image](https://user-images.githubusercontent.com/21196249/50645408-415f2480-0f52-11e9-95bd-e3b883f69cce.png)
 Se sugiere también revisar acentuaciones en "Seleccione especialidad"
![image](https://user-images.githubusercontent.com/21196249/50645478-69e71e80-0f52-11e9-93d9-73de8392d73c.png)
![image](https://user-images.githubusercontent.com/21196249/50645542-93a04580-0f52-11e9-973b-f57c72b3982e.png)

![image](https://user-images.githubusercontent.com/21196249/50645667-deba5880-0f52-11e9-9055-6dee57d4ce54.png)

![image](https://user-images.githubusercontent.com/21196249/50645723-fe518100-0f52-11e9-93df-3bbfd1ff276c.png)

![image](https://user-images.githubusercontent.com/21196249/50645756-0f01f700-0f53-11e9-9c8f-59970fe1d00f.png)

Hora Ingresada correctamente.

Se consultará la Hora asignada rut 10966743
![image](https://user-images.githubusercontent.com/21196249/50646057-ec241280-0f53-11e9-903f-e0c2bdecfce1.png)

![image](https://user-images.githubusercontent.com/21196249/50646153-24c3ec00-0f54-11e9-8853-c52f39ad7b41.png)

### Se confirma Hora

![image](https://user-images.githubusercontent.com/21196249/50646229-56d54e00-0f54-11e9-85fa-4b86deec2f11.png)

![image](https://user-images.githubusercontent.com/21196249/50646275-710f2c00-0f54-11e9-9e06-4d32898e79a9.png)
Confirmada con Éxito.

![image](https://user-images.githubusercontent.com/21196249/50646388-aca9f600-0f54-11e9-972d-91c3f35a215d.png)
Tanto mail de Reserva como de Confirmación llegaron correctamente.
![image](https://user-images.githubusercontent.com/21196249/50646464-e1b64880-0f54-11e9-8021-786d1c09626e.png)

![image](https://user-images.githubusercontent.com/21196249/50646516-0d393300-0f55-11e9-9b1b-eadef85f750c.png)

Ambos correos revisar acentuación en "Médica".

Se consulta Hora Médica Estado cambia a "Confirmada" y desaparece botón en campo Confirmar.

![image](https://user-images.githubusercontent.com/21196249/50646775-b41dcf00-0f55-11e9-9105-363e5a25b4db.png)

### Anular Hora Médica 10966743
![image](https://user-images.githubusercontent.com/21196249/50646843-e92a2180-0f55-11e9-99d8-4f4515b5fea1.png)

![image](https://user-images.githubusercontent.com/21196249/50647663-efb99880-0f57-11e9-91df-328a41db15ac.png)
Hora Anulada con éxito.

### Consultar Anulación Horas Médicas
![image](https://user-images.githubusercontent.com/21196249/50647751-24c5eb00-0f58-11e9-8b0e-7093ffa1b221.png)

![image](https://user-images.githubusercontent.com/21196249/50647819-58a11080-0f58-11e9-88f9-b4e117700ec8.png)
Mensaje correcto.

![image](https://user-images.githubusercontent.com/21196249/50647904-930aad80-0f58-11e9-94bc-35a1e40d42ab.png)

Correo Anulación correcto.

Reserva de Hora Anulada correctamente.

### Resumen
Se realiza Reserva.
Se consulta Reserva y
Se anula Reserva.
Todas estas acciones se realizaron correctamente(llegaron los respectivos mails informando la situación).
Rut utilizado 10966743

Solo quedan pendientes las Observaciones informadas.

### Tarea #20 finalizada.

@felipedonoso @cristsaavedra

**Comment by danteghirardelli** [comment]
### Horas Médicas
![image](https://user-images.githubusercontent.com/21196249/50837261-f66e5400-1339-11e9-9781-d1462ee311da.png)

Se asignará hora a paciente 15348624
![image](https://user-images.githubusercontent.com/21196249/50838544-050a3a80-133d-11e9-916e-41aff02c3295.png)

![image](https://user-images.githubusercontent.com/21196249/50837659-ef941100-133a-11e9-82e7-9b10ab6131fb.png)
![image](https://user-images.githubusercontent.com/21196249/50837773-3d107e00-133b-11e9-8dbe-164585cb96de.png)
![image](https://user-images.githubusercontent.com/21196249/50837802-4c8fc700-133b-11e9-845a-735ba02ffc32.png)
Reserva correcta

### Consulta Reserva
![image](https://user-images.githubusercontent.com/21196249/50838098-fe2ef800-133b-11e9-8ebd-c344ea7dfa48.png)

![image](https://user-images.githubusercontent.com/21196249/50838206-3e8e7600-133c-11e9-9164-ab0f1f4c1c7f.png)

Confirmada con Éxito
![image](https://user-images.githubusercontent.com/21196249/50838229-4d752880-133c-11e9-8f71-41fccef8251f.png)

@cristsaavedra  Observaciones informadas aparecen corregidas.
Muchas gracias.

@felipedonoso @cristsaavedra 
###  Favor cerrar tarea N° 20
