### ISSUE TITLE
<PRUEBA> Recuperar contraseña

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/CAR#21]

**Comment by danteghirardelli** [comment]
### Recuperar Contraseña
![image](https://user-images.githubusercontent.com/21196249/50688986-a6745200-1006-11e9-9d82-c056014ec1b7.png)
![image](https://user-images.githubusercontent.com/21196249/50689028-c99f0180-1006-11e9-9102-3a9c88b20224.png)
![image](https://user-images.githubusercontent.com/21196249/50689051-e1768580-1006-11e9-91e9-65cf6436cd97.png)

### Observación
Sistema envía mensaje de error al intentar recuperar la Contraseña.

@felipedonoso @cristsaavedra

**Comment by danteghirardelli** [comment]
### Recuperar Contraseña:
![image](https://user-images.githubusercontent.com/21196249/50845500-c29c2a00-134b-11e9-93ee-4ac1fbefe0bb.png)

![image](https://user-images.githubusercontent.com/21196249/50845534-d5aefa00-134b-11e9-839e-4be5fcd25641.png)

![image](https://user-images.githubusercontent.com/21196249/50851729-6097f080-135c-11e9-9cb9-67ae95a72fa2.png)

### Credenciales antes del cambio son:

Rut: 11841518
PSW: Gato12345

@felipedonoso @cristsaavedra 

![image](https://user-images.githubusercontent.com/21196249/50852599-c71e0e00-135e-11e9-9386-a3388f0781ac.png)

![image](https://user-images.githubusercontent.com/21196249/50854743-b53f6980-1364-11e9-9818-3b5ccac32b28.png)

![image](https://user-images.githubusercontent.com/21196249/50854753-bcff0e00-1364-11e9-9a66-6efa163298e9.png)

![image](https://user-images.githubusercontent.com/21196249/50854765-c25c5880-1364-11e9-8852-d56a4caad512.png)

![image](https://user-images.githubusercontent.com/21196249/50854845-f768ab00-1364-11e9-9068-c7d56d168746.png)

![image](https://user-images.githubusercontent.com/21196249/50854857-00f21300-1365-11e9-9f97-d39df37b451c.png)

![image](https://user-images.githubusercontent.com/21196249/50854906-25e68600-1365-11e9-8624-82274c56e6f5.png)

![image](https://user-images.githubusercontent.com/21196249/50854917-2aab3a00-1365-11e9-8a93-5143a85b20bb.png)

### Conclusión
Recupera la clave correctamente.

@cristsaavedra @felipedonoso 

Favor Cerrar la tarea N°21
