### ISSUE TITLE
<PRUEBA> Ficha de contacto

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/CAR#22]

**Comment by danteghirardelli** [comment]
### Mantenedor / Ficha de Contacto Deportista crear Nuevo Registro
![image](https://user-images.githubusercontent.com/21196249/50649140-ddd9f480-0f5b-11e9-8660-15d418084b74.png)

![image](https://user-images.githubusercontent.com/21196249/50649270-2abdcb00-0f5c-11e9-8113-1614fdf023a5.png)

###Observación
En Registro Ficha de Contacto Deportistas sección "Deportistas" no se puede optar a ninguno en el listado porque estos no son desplegados.
![image](https://user-images.githubusercontent.com/21196249/50649383-7c665580-0f5c-11e9-88ea-7fe22577d326.png)

@felipedonoso @cristsaavedra 

### Esta tarea quedará STBY porque no se puede avanzar.

**Comment by danteghirardelli** [comment]
@felipedonoso @cristsaavedra 

Ahora Cristian me explicó la lógica de esta tarea.
Primero debo crear un Deportista (sin Ficha de Contacto).
Por lo que haré eso y después sigo con la prueba.

**Comment by danteghirardelli** [comment]
### Se creará un nuevo Deportista
 Mantenedor/Deportistas
![image](https://user-images.githubusercontent.com/21196249/50655017-8ba1cf00-0f6d-11e9-8547-996784041fe1.png)
![image](https://user-images.githubusercontent.com/21196249/50655416-dc65f780-0f6e-11e9-8aca-fc35aaa46a37.png)
![image](https://user-images.githubusercontent.com/21196249/50656281-64e59780-0f71-11e9-8a16-eba4f312a4af.png)
![image](https://user-images.githubusercontent.com/21196249/50656317-8cd4fb00-0f71-11e9-9e3a-2ecf43621342.png)
![image](https://user-images.githubusercontent.com/21196249/50656328-9c544400-0f71-11e9-8628-8e26b4c10a93.png)
![image](https://user-images.githubusercontent.com/21196249/50656374-be4dc680-0f71-11e9-99cc-6ea090e36caa.png)
![image](https://user-images.githubusercontent.com/21196249/50656391-d02f6980-0f71-11e9-92bb-d31a4bae418e.png)
![image](https://user-images.githubusercontent.com/21196249/50656409-e2a9a300-0f71-11e9-9150-a805b69bd00f.png)

![image](https://user-images.githubusercontent.com/21196249/50656464-1684c880-0f72-11e9-8e29-a3a3a7455c28.png)
Mensaje de error.
### Observación
![image](https://user-images.githubusercontent.com/21196249/50656496-30bea680-0f72-11e9-82ab-acdda89e4e1f.png)

Registro Civil trae dentro del campo Nombres.
### El segundo nombre ANDRÉS con acento por lo que no permite avanzar.

### Observación
Dentro del Registro de Deportistas vienen los siguientes campos sin tilde:
Teléfono, Dirección, Ocupación y Práctica.

### Esta tarea quedará STBY mientras se realiza mejora a la acentuación del Campo Nombres.

@felipedonoso @cristsaavedra

**Comment by danteghirardelli** [comment]
### Se probará la Ficha de Contacto:
![image](https://user-images.githubusercontent.com/21196249/50905233-16b51600-1401-11e9-8e90-9aa6e025ac15.png)
![image](https://user-images.githubusercontent.com/21196249/50906179-4bc26800-1403-11e9-9d28-c5895c23265c.png)
![image](https://user-images.githubusercontent.com/21196249/50906208-5d0b7480-1403-11e9-9014-a6418983d455.png)
![image](https://user-images.githubusercontent.com/21196249/50906245-714f7180-1403-11e9-8c82-781d37cd1e4e.png)
![image](https://user-images.githubusercontent.com/21196249/50906265-7e6c6080-1403-11e9-85c4-d21098b61519.png)
Datos ingresados con éxito.
![image](https://user-images.githubusercontent.com/21196249/50906373-b1165900-1403-11e9-9fa7-8bc432e0a4a1.png)

### Se intentará crear nuevamente una Ficha a Deportista 15348624 ya creado
![image](https://user-images.githubusercontent.com/21196249/50906694-69dc9800-1404-11e9-9490-5b8a9284d7d7.png)
![image](https://user-images.githubusercontent.com/21196249/50906841-bc1db900-1404-11e9-81d6-1591e8311d75.png)
Sistema correctamente no permite crear Ficha a un Deportista que ya la posee.
@cristsaavedra Muchas gracias.

### Conclusión
Sistema permite crear la Ficha de Contacto correctamente al Deportista.
Sistema NO permite crear nuevamente Ficha de Contacto a un Deportista que ya la tiene.

@felipedonoso @cristsaavedra 
Favor cerrar Tarea N°22
