### ISSUE TITLE
<PRUEBA> Anular y Confirmar hora

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/CAR#23]

**Comment by danteghirardelli** [comment]
@felipedonoso @cristsaavedra 

Según lo conversado se separa esta prueba para tener un control mas claro de las Pruebas.

### Anular y Confirmar Hora
![image](https://user-images.githubusercontent.com/21196249/50690415-f86ba680-100b-11e9-8ac8-737707d04015.png)
![image](https://user-images.githubusercontent.com/21196249/50690420-fd305a80-100b-11e9-9cff-ed3d7b2f51a3.png)
![image](https://user-images.githubusercontent.com/21196249/50690426-01f50e80-100c-11e9-83ab-5573ec27875e.png)
![image](https://user-images.githubusercontent.com/21196249/50690435-07eaef80-100c-11e9-9773-c2b08d2994e4.png)
![image](https://user-images.githubusercontent.com/21196249/50690442-0e796700-100c-11e9-9c14-d4555e871948.png)
![image](https://user-images.githubusercontent.com/21196249/50690451-1a652900-100c-11e9-839c-93e16b868f13.png)
![image](https://user-images.githubusercontent.com/21196249/50690478-38cb2480-100c-11e9-8b63-60ea1908c135.png)

### Resumen
Se realiza Reserva y anula Reserva.
Todas estas acciones se efectuaron correctamente.
Rut utilizado 10966743

Elflujo completo se hizo en la tarea #20

**Comment by danteghirardelli** [comment]
Se revisarán las observaciones junto con el funcionamiento.
### Anular Horas Médicas  Rut 15348624
![image](https://user-images.githubusercontent.com/21196249/50839230-a6de5700-133e-11e9-9d35-92784c55bfb8.png)
![image](https://user-images.githubusercontent.com/21196249/50839271-ba89bd80-133e-11e9-86b2-7e3821e7fed0.png)
Anulada con éxito.

### Conclusión
Tildes corregidos y funcionalidad correcta.

Favor cerrar la Tarea N°23
