### ISSUE TITLE
<PRUEBA> Asignación de horarios médicos 

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/CAR#25]
Esta prueba consiste en poder asignar un horario médico a un profesional de la saluds.

**Comment by danteghirardelli** [comment]
### Asignación Horas Médicas 
![image](https://user-images.githubusercontent.com/21196249/50922176-9f937800-1428-11e9-8859-90d39f688ad1.png)
![image](https://user-images.githubusercontent.com/21196249/50922244-c8b40880-1428-11e9-99d6-0c793130e546.png)
![image](https://user-images.githubusercontent.com/21196249/50922532-82ab7480-1429-11e9-8545-1e2ab95bb5d2.png)
![image](https://user-images.githubusercontent.com/21196249/50922554-935bea80-1429-11e9-903b-50fd0bbb5a1e.png)
![image](https://user-images.githubusercontent.com/21196249/50922625-bbe3e480-1429-11e9-817c-73926f81f4cf.png)
![image](https://user-images.githubusercontent.com/21196249/50923438-bbe4e400-142b-11e9-84fe-564c4708d7c3.png)
Médico aparece con el día Hora Ingreso y Salida correctas.
Se intenta Guardar nuevamente el Horario del Médico.
Sistema correctamente envía mensaje de error.
![image](https://user-images.githubusercontent.com/21196249/50922680-d8801c80-1429-11e9-8e00-b91bceb01103.png)

### Conclusión
Sistema asigna correctamente  los Horarios de los Médicos.
@felipedonoso @cristsaavedra 

Favor cerrar Tarea N°25

**Comment by danteghirardelli** [comment]
### Se asignará el mismo horario y día en distintos Centros Médicos: 
![image](https://user-images.githubusercontent.com/21196249/50975123-90193b00-14cb-11e9-8e41-69d2ccc427e3.png)
![image](https://user-images.githubusercontent.com/21196249/50976960-facc7580-14cf-11e9-89e4-dc877f83c3e9.png)
![image](https://user-images.githubusercontent.com/21196249/50976965-0029c000-14d0-11e9-82d6-c83cf556f535.png)
![image](https://user-images.githubusercontent.com/21196249/50977041-264f6000-14d0-11e9-9d5e-8315c4009912.png)
Ahora se encuentra reservado para el día Jueves de 10:00 a 14:00 hrs en el CAR.
![image](https://user-images.githubusercontent.com/21196249/50979791-0458dc00-14d6-11e9-9012-da99e958d9c1.png)
![image](https://user-images.githubusercontent.com/21196249/50980538-b6dd6e80-14d7-11e9-9893-4b3c7e476861.png)
![image](https://user-images.githubusercontent.com/21196249/50980586-cfe61f80-14d7-11e9-9cf4-b628932e3804.png)
Mensaje correcto.
Sistema no permite este conflicto de disponibilidad.

@cristsaavedra muchas gracias.
Veré que otro tipo de prueba se puede realizar.

@felipedonoso @cristsaavedra
