### ISSUE TITLE
<hora médica deportista>

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/CAR#26]

**Comment by felipedonoso** [comment]
@danteghirardelli en esta tarea deberás crear una hora médica con tú rut o el mío 15736232-1.

Se deberá verificar lo siguiente:

- Correo de notificación de hora solicitada.
- Formato de correo especificado.

**Comment by danteghirardelli** [comment]
### Reserva de Horas Médicas
![image](https://user-images.githubusercontent.com/21196249/54631553-018ce100-4a5b-11e9-8373-6b7a522c4d02.png)
![image](https://user-images.githubusercontent.com/21196249/54631569-0c477600-4a5b-11e9-981c-a8005352b369.png)
![image](https://user-images.githubusercontent.com/21196249/54631583-12d5ed80-4a5b-11e9-80bd-d2866d62472a.png)
![image](https://user-images.githubusercontent.com/21196249/54631592-179aa180-4a5b-11e9-8e14-636341526ee9.png)
![image](https://user-images.githubusercontent.com/21196249/54631605-1d908280-4a5b-11e9-8390-f02788c54ec7.png)
![image](https://user-images.githubusercontent.com/21196249/54631617-22553680-4a5b-11e9-8863-3e67a5d40fe9.png)
![image](https://user-images.githubusercontent.com/21196249/54631743-5a5c7980-4a5b-11e9-95f2-cc1f14d2a813.png)

### Creación de Deportista 15736232-1
![image](https://user-images.githubusercontent.com/21196249/54631875-a0b1d880-4a5b-11e9-8cf0-b7413334d76a.png)
![image](https://user-images.githubusercontent.com/21196249/54631903-b1fae500-4a5b-11e9-8644-d72bb97d7fd1.png)
![image](https://user-images.githubusercontent.com/21196249/54631928-baebb680-4a5b-11e9-9d30-8c8f2983f855.png)

![image](https://user-images.githubusercontent.com/21196249/54632092-16b63f80-4a5c-11e9-93f9-1d9929b2f3f4.png)
![image](https://user-images.githubusercontent.com/21196249/54632159-39e0ef00-4a5c-11e9-96e5-13c5029d49c7.png)

![image](https://user-images.githubusercontent.com/21196249/54632222-5d0b9e80-4a5c-11e9-99ec-d572e3885531.png)
![image](https://user-images.githubusercontent.com/21196249/54632349-a5c35780-4a5c-11e9-9061-ed8d7a6ff9d4.png)
![image](https://user-images.githubusercontent.com/21196249/54632488-fb97ff80-4a5c-11e9-874d-707bffea1258.png)
![image](https://user-images.githubusercontent.com/21196249/54632693-6f3a0c80-4a5d-11e9-8f1b-57eb1398436a.png)
![image](https://user-images.githubusercontent.com/21196249/54632863-bc1de300-4a5d-11e9-9998-0698f19dffa4.png)
![image](https://user-images.githubusercontent.com/21196249/54632982-01421500-4a5e-11e9-86e7-67832190d4aa.png)
Mensaje.

![image](https://user-images.githubusercontent.com/21196249/54633053-2171d400-4a5e-11e9-8ea8-f814e6a5c214.png)

Mensaje dice "Solo se pueden ingresar valores numericos" debe decir "Solo se pueden ingresar valores numéricos"

![image](https://user-images.githubusercontent.com/21196249/54633172-685fc980-4a5e-11e9-8e88-1db3f367dda7.png)
![image](https://user-images.githubusercontent.com/21196249/54633234-85949800-4a5e-11e9-995a-87af051e6818.png)
![image](https://user-images.githubusercontent.com/21196249/54633287-9e04b280-4a5e-11e9-9164-222e44a3247e.png)
Mensaje correcto.

### Conclusión
- Se crea Deportista 15736232-1 correctamente.

@felipedonoso @cristsaavedra 

Ahora se agendará una Hora médica al Deportista.

**Comment by danteghirardelli** [comment]
### Agendar Horas Médicas al Deportista 15736232-1
![image](https://user-images.githubusercontent.com/21196249/54635156-554ef880-4a62-11e9-8962-9ee24907dc57.png)
![image](https://user-images.githubusercontent.com/21196249/54635755-a4495d80-4a63-11e9-9930-8dbaa1de2d07.png)
![image](https://user-images.githubusercontent.com/21196249/54635783-b4f9d380-4a63-11e9-969d-a2ec7e7f0b03.png)
![image](https://user-images.githubusercontent.com/21196249/54635833-d35fcf00-4a63-11e9-9934-97f1f7beb728.png)
![image](https://user-images.githubusercontent.com/21196249/54635844-dfe42780-4a63-11e9-9154-eccfef8b4159.png)
![image](https://user-images.githubusercontent.com/21196249/54635958-1ae65b00-4a64-11e9-9877-f18adab5e0b5.png)
![image](https://user-images.githubusercontent.com/21196249/54636034-3fdace00-4a64-11e9-96d1-55739b790974.png)
![image](https://user-images.githubusercontent.com/21196249/54636063-52550780-4a64-11e9-86eb-35746a82c9fc.png)
Mensaje correcto.

### Mail
![image](https://user-images.githubusercontent.com/21196249/54636515-60575800-4a65-11e9-9e85-89638ad17607.png)
![image](https://user-images.githubusercontent.com/21196249/54636544-706f3780-4a65-11e9-80a1-fa97477c9b2f.png)
![image](https://user-images.githubusercontent.com/21196249/54636568-7d8c2680-4a65-11e9-8713-d771955d2a41.png)

### Consultar Hora Médica
![image](https://user-images.githubusercontent.com/21196249/54636806-fab79b80-4a65-11e9-84fb-bc5148aff94c.png)
![image](https://user-images.githubusercontent.com/21196249/54636854-10c55c00-4a66-11e9-85d8-206e8dc969f2.png)
Mensaje correcto.

Se ingresa Número Reserva
![image](https://user-images.githubusercontent.com/21196249/54636963-4bc78f80-4a66-11e9-9657-fd16609c5e7b.png)
![image](https://user-images.githubusercontent.com/21196249/54637085-9e08b080-4a66-11e9-97f1-eb215aa54630.png)

Despliega correctamente la Reserva Número 5
### Confirmar Hora
![image](https://user-images.githubusercontent.com/21196249/54637124-ad87f980-4a66-11e9-80ac-020cab74fac9.png)

### Conclusión:
- Se Agenda correctamente la Reserva.
@felipedonoso  @cristsaavedra

**Comment by cristsaavedra** [comment]
Corrección de palabra (numúricos) se ha realizado sin problemas,

**Comment by danteghirardelli** [comment]
@felipedonoso @cristsaavedra 

Cristian muchas gracias.
Ahora seguiré con las pruebas.

**Comment by danteghirardelli** [comment]
### Anulación Horas Médicas
![image](https://user-images.githubusercontent.com/21196249/54683179-c25c9f80-4aef-11e9-9ac9-fa8b80ff6f99.png)

![image](https://user-images.githubusercontent.com/21196249/54683528-a0afe800-4af0-11e9-9fb8-078dae16085a.png)

### Confirmar Anulación Hora Médica Individual
![image](https://user-images.githubusercontent.com/21196249/54683601-cf2dc300-4af0-11e9-8b39-36981baab84f.png)

![image](https://user-images.githubusercontent.com/21196249/54683638-e8367400-4af0-11e9-9f3a-7f3f117b1beb.png)

### Mail de Anulación
![image](https://user-images.githubusercontent.com/21196249/54683705-174ce580-4af1-11e9-849e-a20f1daf6c00.png)
![image](https://user-images.githubusercontent.com/21196249/54683762-406d7600-4af1-11e9-88c2-246eb011537a.png)
![image](https://user-images.githubusercontent.com/21196249/54683781-4fecbf00-4af1-11e9-8629-1276ef016e07.png)

### Consultar Hora Médica Anulada y Confirmada
![image](https://user-images.githubusercontent.com/21196249/54683883-9510f100-4af1-11e9-90a3-092b3c61c0a5.png)
![image](https://user-images.githubusercontent.com/21196249/54683914-ab1eb180-4af1-11e9-9310-9ff3b134a1ca.png)
Mensaje correcto.

### Conclusión:
- Sistema Anula y confirma correctamente las horas individuales.
@felipedonoso @cristsaavedra 

Ahora veré la Anulación de Hora por Bloque.

**Comment by danteghirardelli** [comment]
### Anular Horas por Bloque
Dr Álvaro Zamorano/ Traumatología

Paciente 13294125 Día 22-03-19 /11:40 hrs /Reserva 7
Paciente 15736232 Día 22-03-19 / 12:00 hrs /Reserva 11

![image](https://user-images.githubusercontent.com/21196249/54692405-ba0e5f80-4b03-11e9-979e-9b741b61ff27.png)

![image](https://user-images.githubusercontent.com/21196249/54692623-0bb6ea00-4b04-11e9-93de-b8f5c31449da.png)
### Cancelar Bloque Completo
![image](https://user-images.githubusercontent.com/21196249/54692793-559fd000-4b04-11e9-8c46-3aeb0bf1b8f6.png)
![image](https://user-images.githubusercontent.com/21196249/54692857-6d775400-4b04-11e9-80a1-5495e16beccb.png)
Mensaje de Anulación

![image](https://user-images.githubusercontent.com/21196249/54692920-87b13200-4b04-11e9-899f-efc5d81e7e27.png)
Bloque Anulado

Mails
![image](https://user-images.githubusercontent.com/21196249/54693061-c7781980-4b04-11e9-9a78-3e39cb15d753.png)
![image](https://user-images.githubusercontent.com/21196249/54693121-d9f25300-4b04-11e9-9c14-1c71fe50987b.png)

### Conclusión:
- Anulación de Horas por Bloque es correcto.

### Observaciones:
- Mantenedor/Reserva Horas Medicas(Sin tilde en Médicas)
![image](https://user-images.githubusercontent.com/21196249/54693676-c7c4e480-4b05-11e9-8d55-42ddd5f8225c.png)
- Mensaje de Anulación falta tilde en Médicas. 
![image](https://user-images.githubusercontent.com/21196249/54693765-f17e0b80-4b05-11e9-9b32-41e8f351d301.png)
- Encabezado de mail de Anulación. Sistema dice Anulación Hora Medica(falta tilde en Médica).
![image](https://user-images.githubusercontent.com/21196249/54693912-2d18d580-4b06-11e9-8a23-a23d1392cf2c.png)

### Observación Extra:
- Al cerrar Sesión
![image](https://user-images.githubusercontent.com/21196249/54694115-779a5200-4b06-11e9-8725-d701fbeba8a3.png)

Sistema envía mensaje de Error:
Server Error
404 - File or directory not found
![image](https://user-images.githubusercontent.com/21196249/54694256-b6c8a300-4b06-11e9-96ed-f57f6f0ada1d.png)

@felipedonoso @cristsaavedra 

Si tienen alguna consulta me dicen.

**Comment by danteghirardelli** [comment]
### Revisión General
Mantenedor de Usuarios
![image](https://user-images.githubusercontent.com/21196249/54701304-7de2fb00-4b13-11e9-8eed-ea2d454b6a9c.png)

Registro de Usuarios
![image](https://user-images.githubusercontent.com/21196249/54701524-ec27bd80-4b13-11e9-9953-7c23e2123780.png)

Sugerencias:
![image](https://user-images.githubusercontent.com/21196249/54701855-8ab41e80-4b14-11e9-8ed6-4589040d75a8.png)
Limitar el ingreso de letras, números y caracteres extraños en los campos Nombres, Apellido Paterno y Apellido Materno.
Respecto al campo Correo limitar el ingreso de letras, números y caracteres extraños.
Con eso se minimiza el error al intentar Guardar.
![image](https://user-images.githubusercontent.com/21196249/54702277-4f661f80-4b15-11e9-90cc-aeaf4b898685.png)
Mensaje correcto.

Mantenedor/ Áreas Médicas
![image](https://user-images.githubusercontent.com/21196249/54702596-ed59ea00-4b15-11e9-9a9e-3bff301cb900.png)

![image](https://user-images.githubusercontent.com/21196249/54702706-2a25e100-4b16-11e9-9f65-fd4b0a102336.png)
Buscar aparece en Inglés (Search)

Nuevo registro
![image](https://user-images.githubusercontent.com/21196249/54702904-8d177800-4b16-11e9-8014-67a251f2c77d.png)

Registro de Áreas Médicas
Dentro del campo Área Médica falta tildes para Área Médica.
![image](https://user-images.githubusercontent.com/21196249/54703228-1af36300-4b17-11e9-9311-1c6264a5c394.png)

Guardar Registro en Área Médica -  Test Médico 
![image](https://user-images.githubusercontent.com/21196249/54703430-8e957000-4b17-11e9-8203-059f46756bc9.png)
![image](https://user-images.githubusercontent.com/21196249/54703448-9c4af580-4b17-11e9-9541-941c9957f199.png)
Mensaje correcto.

Editar Test Médico
![image](https://user-images.githubusercontent.com/21196249/54703698-095e8b00-4b18-11e9-9d14-30e0c540b540.png)

![image](https://user-images.githubusercontent.com/21196249/54703779-3743cf80-4b18-11e9-8f50-f94fbc4d5767.png)
Mensaje correcto.
![image](https://user-images.githubusercontent.com/21196249/54703827-4f1b5380-4b18-11e9-950d-18950a1cbc1e.png)
Editado correctamente.

@felipedonoso @cristsaavedra 
Observaciones/ Sugerencias indicadas en las pantallas.

Ahora se continúa con Mantenedor/ Centros Médicos

**Comment by danteghirardelli** [comment]
### Mantenedor/Centros Médicos
![image](https://user-images.githubusercontent.com/21196249/54711727-60b92700-4b29-11e9-9173-93eeacc9bae9.png)
![image](https://user-images.githubusercontent.com/21196249/54711817-90682f00-4b29-11e9-9925-c6b372f88ba5.png)
![image](https://user-images.githubusercontent.com/21196249/54711861-a2e26880-4b29-11e9-9cdf-d7ab2b718b0a.png)
Ingresar Nuevo Registro
![image](https://user-images.githubusercontent.com/21196249/54712537-4b44fc80-4b2b-11e9-96c6-58fa68bcf558.png)
![image](https://user-images.githubusercontent.com/21196249/54712551-526c0a80-4b2b-11e9-8253-ab1f8fafb70c.png)
![image](https://user-images.githubusercontent.com/21196249/54712649-98c16980-4b2b-11e9-93ca-7502fc766490.png)
![image](https://user-images.githubusercontent.com/21196249/54712706-bbec1900-4b2b-11e9-90c3-2c764afe19e9.png)
Mensaje correcto
![image](https://user-images.githubusercontent.com/21196249/54712752-d7572400-4b2b-11e9-9487-6a6764dfdfdb.png)
Editar Centro Médico
![image](https://user-images.githubusercontent.com/21196249/54712786-f0f86b80-4b2b-11e9-8d94-e9d029aab7b8.png)
![image](https://user-images.githubusercontent.com/21196249/54712823-0b324980-4b2c-11e9-89f3-d380489c29a9.png)
![image](https://user-images.githubusercontent.com/21196249/54712846-17b6a200-4b2c-11e9-82c9-8cf152bf2a89.png)
Mensaje correcto
![image](https://user-images.githubusercontent.com/21196249/54712916-39b02480-4b2c-11e9-9636-02fc7a5bf603.png)
Eliminar Centro Médico
![image](https://user-images.githubusercontent.com/21196249/54713044-724ffe00-4b2c-11e9-9d80-bdf028ea9f36.png)
![image](https://user-images.githubusercontent.com/21196249/54713075-8136b080-4b2c-11e9-9cf2-a3614b424caf.png)
![image](https://user-images.githubusercontent.com/21196249/54713100-901d6300-4b2c-11e9-88c6-109fde92507a.png)
Sistema no lo elimina solo lo deja como "No" en el campo Activo
![image](https://user-images.githubusercontent.com/21196249/54713213-df639380-4b2c-11e9-86a3-733a172015ea.png)

### Conclusión:
- Sistema crea correctamente el Centro Médico

### Observaciones
- Comienzo con mayúsculas(cambiar)
![image](https://user-images.githubusercontent.com/21196249/54713690-f8b90f80-4b2d-11e9-9c06-02c4a3cc80b9.png)
- Palabras en Inglés
![image](https://user-images.githubusercontent.com/21196249/54713727-09698580-4b2e-11e9-8ebf-fe3e9dc090db.png)
- Falta de Tildes
![image](https://user-images.githubusercontent.com/21196249/54713744-19816500-4b2e-11e9-8550-56a74425a3b2.png)
- ¿No lo elimina totalmente solo lo cambia de Activo a Inactivo?
![image](https://user-images.githubusercontent.com/21196249/54713820-4cc3f400-4b2e-11e9-942c-499dbe0b775f.png)

@felipedonoso @cristsaavedra 

Muchas gracias.

### Ahora continuaré con Condición Deportistas

**Comment by cristsaavedra** [comment]
Observaciones corregidas, favor revisar y validar.
