### ISSUE TITLE
Registrar DEPORTISTA

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/CAR#33]
@danteghirardelli 

El link para acceder es el siguiente:

http://10.15.1.51/car/Login/Index

También podrás agendar hora con los siguientes perfiles:

Secretaría:

Rut: 6370645
Contraseña: 12345

Médico

Rut: 10950514
Contraseña: 12345

**Comment by danteghirardelli** [comment]
### Registrar Deportista
Link
http://10.15.1.51/car/Login/Index

Agendar con Perfiles:

Secretaría:
Rut: 6370645
Contraseña: 12345

Médico
Rut: 10950514
Contraseña: 12345

Secretaria
![image](https://user-images.githubusercontent.com/21196249/55104645-8e621b00-50a9-11e9-93a6-f4da1e5231d0.png)
![image](https://user-images.githubusercontent.com/21196249/55104706-aafe5300-50a9-11e9-93f7-e91fe882b456.png)

![image](https://user-images.githubusercontent.com/21196249/55104771-ccf7d580-50a9-11e9-8df3-fb3a7f217731.png)
![image](https://user-images.githubusercontent.com/21196249/55105038-5c04ed80-50aa-11e9-858b-f5f25f220984.png)
Mensaje por Perfil

### Ingreso Nuevo Deportista
![image](https://user-images.githubusercontent.com/21196249/55105208-c4ec6580-50aa-11e9-842d-247fbf52ee7c.png)

![image](https://user-images.githubusercontent.com/21196249/55105307-ff560280-50aa-11e9-9c2a-cbffbdb08cbb.png)
Rut 11934132-9
![image](https://user-images.githubusercontent.com/21196249/55105475-61166c80-50ab-11e9-8554-247fbaac172b.png)
![image](https://user-images.githubusercontent.com/21196249/55105568-97ec8280-50ab-11e9-8e40-58e8794ff09a.png)
![image](https://user-images.githubusercontent.com/21196249/55105645-c5d1c700-50ab-11e9-965d-975c3d705869.png)
![image](https://user-images.githubusercontent.com/21196249/55105726-fc0f4680-50ab-11e9-861b-06eed5d572c9.png)
![image](https://user-images.githubusercontent.com/21196249/55105766-1812e800-50ac-11e9-8fd6-600d0ac64815.png)
![image](https://user-images.githubusercontent.com/21196249/55105785-23feaa00-50ac-11e9-9d8f-51c9f4217706.png)
Mensaje correcto.

![image](https://user-images.githubusercontent.com/21196249/55105848-4abce080-50ac-11e9-80e5-cfc437ea81ef.png)


### Conclusión:
- Sistema Registra correctamente al Deportista Rut 11934132-9
- Sistema pide completar Flag de Consentimiento Informado.

@felipedonoso @cristsaavedra 

Cristian, muchas gracias.

Si tienen alguna consulta me dicen.
Favor cerrar tarea.
