### ISSUE TITLE
<RE-AGENDAR HORAS A UN MES POSTERIOR>

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/CAR#44]
Este error ocurrió al momento de cancelar una hora y recuperarla en un mes posterior.

El caso fue el siguiente:

Ahora el idEstadoFicha = 7

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/ea695dcb-ebeb-4770-bafd-629f1dd72745)

Se dejará en el estado previo a la prueba en idEstadoFicha = 1.

**Comment by felipedonoso** [comment]
Se revisa el horario del día 28 de junio para Álvaro Zamorano:

![image](https://user-images.githubusercontent.com/5757157/56610040-90ea5e80-65dc-11e9-9505-3c6eed758553.png)

Ahora se creará la jornada del día martes:

![image](https://user-images.githubusercontent.com/5757157/56610242-fa6a6d00-65dc-11e9-8d08-7d429a927471.png)

![image](https://user-images.githubusercontent.com/5757157/56610265-05250200-65dd-11e9-942e-4cb1914d143f.png)

Ahora se guardará para el mismo día:

![image](https://user-images.githubusercontent.com/5757157/56610346-34d40a00-65dd-11e9-977e-5e8c96a18485.png)

Se cambia el horario para un día anterior: 27-junio.

**Comment by felipedonoso** [comment]
Se revisará si el cambio fue realizado con éxito:

![image](https://user-images.githubusercontent.com/5757157/56610595-ca6f9980-65dd-11e9-9ba2-9329f8c69796.png)

La observación que se realizar es la siguiente:

**Hora: 11:20**, aparece **disponible** en el lado izquierdo que es él "Antes" y en el nuevo horario aparece como solicitada por **Cristián Villalobos.**

![image](https://user-images.githubusercontent.com/5757157/56610845-73b68f80-65de-11e9-83d3-6acd528e16ca.png)

![image](https://user-images.githubusercontent.com/5757157/56610852-7ca76100-65de-11e9-80b3-18244f5418d3.png)

**Comment by felipedonoso** [comment]
Revisando en la base de datos:

La hora fue cancelada: el estado cambio de 1 a 7.

![image](https://user-images.githubusercontent.com/5757157/56611098-022b1100-65df-11e9-82f6-2ccf182b238b.png)

![image](https://user-images.githubusercontent.com/5757157/56611325-81b8e000-65df-11e9-89c7-e2ef7a9f3c0d.png)

Esto esta correcto 👍 

Ahora revisando el error de la hora: **11:20.**

![image](https://user-images.githubusercontent.com/5757157/56611484-e70cd100-65df-11e9-896a-bf7eeef4fda7.png)

**Resultados del día 28 y 27 de junio:**

**NOTA:** Aparece uno con id=4 que es eliminado x médico.

![image](https://user-images.githubusercontent.com/5757157/56611773-a95c7800-65e0-11e9-8abc-56a9cfb86d1c.png)

**Comment by felipedonoso** [comment]
Se realizará en el mes de agosto: 02 AGOSTO no hay horas agendadas.

![image](https://user-images.githubusercontent.com/5757157/56613864-8e403700-65e5-11e9-91d6-2b17d1c6a26e.png)

Se crearán horas para el día:  09 junio

![image](https://user-images.githubusercontent.com/5757157/56614370-e297e680-65e6-11e9-9cb4-6937bbdd4e19.png)

**Comment by felipedonoso** [comment]
Ahora todas las horas del día 09 de Agosto al 01:

Se presiono el botón CANCELAR:

![image](https://user-images.githubusercontent.com/5757157/56614753-c47eb600-65e7-11e9-8016-928946be95ce.png)

Si bien aparece el mensaje cambio realizado con éxito, este no se realizo:

**Comment by felipedonoso** [comment]
Se cambia la fecha al 01 de agosto e indica que se realizo sin problemas:

![image](https://user-images.githubusercontent.com/5757157/56615154-833ad600-65e8-11e9-978f-4ac621d1e03c.png)

En la base de datos las horas canceladas: 09 agosto:

![image](https://user-images.githubusercontent.com/5757157/56615295-c5fcae00-65e8-11e9-8c99-2318ac947c83.png)

Y ahora los del día 01 de agosto:

![image](https://user-images.githubusercontent.com/5757157/56615363-eb89b780-65e8-11e9-9d7a-8ba328ed55e7.png)

**Comment by cristsaavedra** [comment]
Felipe, 

Efectivamente el mensaje es el correcto ya que se le esta preguntando al usuario lo siguiente: 

¿Desea cambiar las horas médicas agendadas del día que desea cancelar al nuevo día y horario?
por lo cual aparecen 2 botones, uno de confirmar y otro de cancelar.

Para evitar una mala interpretación de los botones ahora se dejaron como un Si y No para que los botones estén con referencia a la pregunta que se le esta haciendo al usuario.

![image](https://user-images.githubusercontent.com/40171432/56660219-0ef64600-666d-11e9-84f9-e8ca8c98dec6.png)

**Comment by felipedonoso** [comment]
# Conclusión:

**Esta terminado y con la mejora del mensaje de cambio de jornada.**
